## Configuration file for Jekyll & Schrift template

#
# Jekyll configuration
#

# Global
safe: false
url: http://bootex.github.io/
source:      .
destination: ./_site
plugins:     ./_plugin

# Server
port: 4000

# Build options
future:      true
lsi:         false
highlighter: rouge
# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables", "with_toc_data"]

permalink:   date
auto_ids:    true

#fenced_code_blocks: true
#

# Schrift template configuration
#

# Enter below your name or pseudo & a short description
#    | These don't appear on the website. They are used to set the <META>s
author: Bootex(MinorCreator)
description: Computer programmer interested in security and machine learning.
title: Bootex page  # Appears in the window title of the browser. Stands alone on the homepage, sits beside the post title on post pages.

# Enter below the headtitle of your weblog/website
#    | It appears on the main navigation bar. You use <span></span> to nicely fade out some part of it
maintitle: Bootex <span>for blog</span>

# Enter below a short description that will sit next to your head title.
#    | {optional}
maindesc: <a href=https://github.com/Bootex/pages><span class=oi data-glyph=fork></span> Fork me</a>

# Enter below the items of your main menu
#    | Keep it a small amount. It is designed for a small menu.
menus:
- text: Archive
  url: /menus/archive.html
  openiconic: list

- text: projects
  url: /menus/projects.html
  openiconic: list-rich

- text: About
  url: /about.html
  openiconic: list-rich

- text: tags
  url: /menus/tags.html
  openiconic: list

- text: Contact
  url: /menus/contact.html
  openiconic: info
  
# Enter an invitation message
#    | It lies right beneath every post to invite your readers to react and comment
#    | {optional}
invitationmsg: If you have any feedback you would like me to read, please don't hesitate to send them over to <a href=mailto:furorluna@gmail.com>furorluna@gmail.com</a>.
